sudo: required
dist: trusty
compiler:
  - gcc
env:
  global:
    - LUAROCKS=2.3.0
    - CC=gcc-7
    - CXX=g++-7
  matrix:
    - LUA="lua 5.1"
branches:
  only:
    - master
before_install:
  - sudo pip install hererocks
  - hererocks ~/hererocks -r^ --$LUA --cflags=$LUA_CFLAGS
  - export PATH=$PATH:~/hererocks/bin
  - eval $(luarocks path --bin)
  - luarocks install luacheck
  - luarocks install luacov-coveralls
  - luarocks install busted
install:
  - luarocks install --only-deps rockspec/euluna-dev-0.rockspec
script:
  - busted -c
after_success:
  - luacov-coveralls -v